spring:
  application:
    name: gabinova-backend
  data:
    mongodb:
      uri: mongodb+srv://nexus_admin:nexus123456@cluster0.btimxem.mongodb.net/gabinova?retryWrites=true&w=majority&appName=Cluster0
  jackson:
    default-property-inclusion: non_null

server:
  port: ${PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET:nexus-aguia-challenge-fiap-jwt-secret-troque-em-producao-32b}
  expiration-hours: ${JWT_EXPIRATION_HOURS:8}

springdoc:
  swagger-ui:
    path: /docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    br.com.fiap.gabinova.backend: INFO
